name: Java CI
on: [push]
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: "14"
          distribution: "adopt"
      - name: Build and test with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Generate coverage report
        run: mvn jacoco:report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./target/site/jacoco/
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./index.xml
          verbose: true
